kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-bak-data-pv-volume
  annotations:
        "volume.alpha.kubernetes.io/node-affinity": '{
            "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                    { "matchExpressions": [
                        { "key": "kubernetes.io/hostname",
                          "operator": "In",
                          "values": ["k8s13","k8s14"]
                        }
                    ]}
                 ]}
              }'
  namespace: es-bak
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/component/dev-es-bak"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-bak-pvc
  namespace: es-bak
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data
  namespace: es-bak
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data
  replicas: 2
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - data
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        es: test
      initContainers:
      - name: init-sysctl
        image: registry.yingzi.com:8500/library/busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-data
        image: registry.yingzi.com:8500/library/elasticsearch/elasticsearch:6.4.2.4
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: my-es
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "false"
        - name: XPACK_SECURITY_ENABLED
          value: "true"
        - name: XPACK_SECURITY_TRANSPORT_SSL_ENABLED
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms2048m -Xmx2048m
        - name: "NETWORK_HOST"
          value: "_eth0_"
        - name: NUMBER_OF_MASTERS
          value: "2"
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-discovery:9300"
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          limits:
            cpu: 2
        ports:
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: localstorage
          mountPath: /usr/share/elasticsearch/data
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localstorage   
          persistentVolumeClaim:         
            claimName: es-bak-pvc
        - name: localtime
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  namespace: es-bak
  labels:
    component: elasticsearch
    role: data
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    component: elasticsearch
    role: data

